// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"
import { Tabs, Toggle, Dropdown, Modal } from "tailwindcss-stimulus-components"
import * as ActiveStorage from "@rails/activestorage"
import NavbarController from "./navbar_controller"
import SliderController from "./slider_controller"

ActiveStorage.start()
application.register("navbar", NavbarController)
application.register("slider", SliderController)
application.register('tabs', Tabs)
application.register('toggle', Toggle)
application.register('dropdown', Dropdown)
application.register('modal', Modal)